name: colourswift_av
description: ColourSwift AV+ - standalone antivirus suite using the Rust engine.
publish_to: "none"
version: 2.0.2+11492
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  ffi: ^2.1.4
  permission_handler: ^11.4.0
  path_provider: ^2.1.4
  path: ^1.9.0
  shared_preferences: ^2.3.2
  percent_indicator: ^4.2.3
  animate_do: ^3.3.4
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  intl: ^0.20.2
  provider: ^6.1.2
  file_picker: ^8.1.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  installed_apps: ^2.0.0
  cryptography: ^2.7.0
  flutter_secure_storage: ^9.2.2
  device_apps: ^2.2.0
  usage_stats: ^1.3.1
  video_thumbnail: ^0.5.3
  video_player: ^2.9.1
  photo_view: ^0.15.0
  open_filex: ^4.7.0
  url_launcher: ^6.3.2
  receive_intent: ^0.2.7
  package_info_plus: ^8.0.0
  device_info_plus: ^12.2.0
  android_intent_plus: ^4.0.3
  in_app_purchase: ^3.2.0

dev_dependencies:
  flutter_launcher_icons: ^0.14.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

dependency_overrides:
  device_apps:
    path: plugins/device_apps-2.2.0
  usage_stats:
    path: plugins/usage_stats-fixed
flutter:
  uses-material-design: true
  assets:
    - assets/icons/logo.png
    - assets/images/logo.png
    - assets/defs/defs.vxpack
    - assets/defs/defs_key.bin
    - assets/icons/ic_launcher_default.png
    - assets/icons/ic_launcher_bird.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  remove_alpha_ios: true

